### ISSUE TITLE
TypeError: DeepObservable is not a constructor

### ISSUE THREAD

**Issue by m-mujica** [canjs/can-deep-observable#8]
Isn't `DeepObservable` meant to be used as a costructor as well?  https://canjs.com/doc/can-deep-observable.html

**Comment by m-mujica** [comment]
https://github.com/canjs/can-deep-observable/compare/test?expand=1

**Comment by cherifGsoul** [comment]
I'm not sure if this needs to be fixed in the code since `DeepObservable` is a plain object.
It can be instantiated using `canReflect.new`.
I guess the usage in the documentation is wrong.
cc @phillipskevin

**Comment by cherifGsoul** [comment]
This is fixed in #9
